/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMonitoramentoRouteImport } from './routes/app.monitoramento'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAlertasRouteImport } from './routes/app.alertas'
import { Route as AppMetricasMetricRouteImport } from './routes/app.metricas.$metric'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoramentoRoute = AppMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricasMetricRoute = AppMetricasMetricRouteImport.update({
  id: '/metricas/$metric',
  path: '/metricas/$metric',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/app/metricas/$metric': typeof AppMetricasMetricRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app': typeof AppIndexRoute
  '/app/metricas/$metric': typeof AppMetricasMetricRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/monitoramento': typeof AppMonitoramentoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/app/metricas/$metric': typeof AppMetricasMetricRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/esqueci-senha'
    | '/login'
    | '/onboarding'
    | '/redefinir-senha'
    | '/signup'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/monitoramento'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/'
    | '/app/metricas/$metric'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/onboarding'
    | '/redefinir-senha'
    | '/signup'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/monitoramento'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app'
    | '/app/metricas/$metric'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/esqueci-senha'
    | '/login'
    | '/onboarding'
    | '/redefinir-senha'
    | '/signup'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/monitoramento'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/'
    | '/app/metricas/$metric'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoramento': {
      id: '/app/monitoramento'
      path: '/monitoramento'
      fullPath: '/app/monitoramento'
      preLoaderRoute: typeof AppMonitoramentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metricas/$metric': {
      id: '/app/metricas/$metric'
      path: '/metricas/$metric'
      fullPath: '/app/metricas/$metric'
      preLoaderRoute: typeof AppMetricasMetricRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppMonitoramentoRoute: typeof AppMonitoramentoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMetricasMetricRoute: typeof AppMetricasMetricRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppMonitoramentoRoute: AppMonitoramentoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppMetricasMetricRoute: AppMetricasMetricRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
